import { Inter } from 'next/font/google'
import {Layout} from "@/components";
import '@/styles/globals.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Layout>
        {children}
      </Layout>
      </body>
    </html>
  )
}
